"use client";

import { useMemo, useState } from "react";
import { DollarSign, Trophy, X, Zap } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import CrittersMap from "@/components/critters/CrittersMap";
import { ELECTRICITY_BANDS, ELECTRICITY_DATASET, type ElectricityStateValue } from "@/lib/electricity";

const price = (value: number) => `${value.toFixed(2)}¢`;

export default function ElectricityClient() {
  const [selected, setSelected] = useState<string | null>(null);
  const data = ELECTRICITY_DATASET.data;
  const selectedState = useMemo(() => data.find((row) => row.state === selected) ?? null, [data, selected]);
  const expensive = useMemo(() => [...data].sort((a, b) => b.priceCentsPerKwh - a.priceCentsPerKwh), [data]);
  const lowCount = data.filter((row) => row.priceCentsPerKwh <= 14).length;

  return <div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-3xl text-sm text-muted-foreground">Average residential retail price, not a monthly bill. Hover a state for its rate and click to pin its detail.</p><Badge variant="secondary">Preliminary EIA-861M estimates</Badge></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <StatCard icon={<Trophy className="size-4" />} label="Lowest price" value="North Dakota" sub="11.92¢/kWh" />
      <StatCard icon={<DollarSign className="size-4" />} label="U.S. average" value={price(ELECTRICITY_DATASET.nationalAverage)} sub="per kilowatthour" />
      <StatCard icon={<Zap className="size-4" />} label="At or below 14¢" value={String(lowCount)} sub="states" />
      <StatCard icon={<Trophy className="size-4" />} label="Highest price" value="Hawaii" sub="44.61¢/kWh" />
    </div>
    <div className="grid gap-6 lg:grid-cols-3">
      <Card className="lg:col-span-2"><CardHeader><CardTitle>Residential electricity price by state</CardTitle><CardDescription>{ELECTRICITY_DATASET.period}; colors use price brackets to keep continental-state differences legible.</CardDescription></CardHeader><CardContent className="space-y-4"><CrittersMap data={data} unit="¢/kWh" selected={selected} onSelect={setSelected} bandLabel={(row) => (row as ElectricityStateValue).priceBand} colorForStat={(row) => ELECTRICITY_BANDS.find((band) => band.matches((row as ElectricityStateValue).priceCentsPerKwh))?.color ?? "var(--muted)"} /><Legend /></CardContent></Card>
      {selectedState ? <SelectedCard state={selectedState} onClear={() => setSelected(null)} /> : <ExpensiveCard data={expensive} onSelect={setSelected} />}
    </div>
    <Card><CardHeader><CardTitle>Full state ranking</CardTitle><CardDescription>Rank 1 is the lowest average residential price.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="border-b text-xs text-muted-foreground"><tr><th className="px-2 py-2 text-left font-medium">Rank</th><th className="px-2 py-2 text-left font-medium">State</th><th className="px-2 py-2 text-right font-medium">Residential price</th><th className="px-2 py-2 text-right font-medium">Affordability score</th><th className="px-2 py-2 text-left font-medium">Price band</th></tr></thead><tbody>{data.map((state) => <tr key={state.state} className="border-b last:border-0 hover:bg-muted/50"><td className="px-2 py-2 tabular-nums">{state.rank}</td><td className="px-2 py-2 font-medium">{state.name}</td><td className="px-2 py-2 text-right font-semibold tabular-nums">{price(state.priceCentsPerKwh)}/kWh</td><td className="px-2 py-2 text-right tabular-nums">{state.affordabilityScore.toFixed(1)} / 100</td><td className="px-2 py-2"><Badge className="border-transparent text-white" style={{ background: ELECTRICITY_BANDS.find((band) => band.matches(state.priceCentsPerKwh))?.color }}>{state.priceBand}</Badge></td></tr>)}</tbody></table></div></CardContent></Card>
    <Sources />
  </div>;
}

function Legend() { return <div className="space-y-2"><div className="flex items-center gap-3"><span className="text-xs text-muted-foreground">Lower price</span><div className="flex h-2.5 flex-1 overflow-hidden rounded-full">{ELECTRICITY_BANDS.map((band) => <span key={band.label} className="flex-1" style={{ background: band.color }} />)}</div><span className="text-xs text-muted-foreground">Higher price</span></div><div className="flex flex-wrap gap-x-4 gap-y-1">{ELECTRICITY_BANDS.map((band) => <span key={band.label} className="flex items-center gap-1.5 text-xs text-muted-foreground"><span className="size-2.5 rounded-[3px]" style={{ background: band.color }} />{band.label}</span>)}</div></div>; }
function StatCard({ icon, label, value, sub }: { icon: React.ReactNode; label: string; value: string; sub: string }) { return <Card><CardContent className="flex flex-col gap-1"><div className="flex items-center gap-1.5 text-muted-foreground">{icon}<span className="text-xs font-medium">{label}</span></div><div className="truncate text-xl font-bold leading-tight" title={value}>{value}</div><div className="text-xs text-muted-foreground">{sub}</div></CardContent></Card>; }
function ExpensiveCard({ data, onSelect }: { data: ElectricityStateValue[]; onSelect: (state: string) => void }) { return <Card><CardHeader><CardTitle>Top 10 most expensive</CardTitle><CardDescription>Highest average residential price</CardDescription></CardHeader><CardContent className="space-y-2.5">{data.slice(0, 10).map((state) => <button key={state.state} onClick={() => onSelect(state.state)} className="flex w-full items-center gap-3 rounded-md px-1.5 py-1 text-left transition-colors hover:bg-muted"><span className="w-5 text-xs font-semibold tabular-nums text-muted-foreground">{state.rank}</span><span className="w-28 shrink-0 truncate text-sm font-medium">{state.name}</span><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-orange-800" style={{ width: `${(state.priceCentsPerKwh / data[0].priceCentsPerKwh) * 100}%` }} /></div><span className="w-12 text-right text-xs font-semibold tabular-nums">{price(state.priceCentsPerKwh)}</span></button>)}</CardContent></Card>; }
function SelectedCard({ state, onClear }: { state: ElectricityStateValue; onClear: () => void }) { const difference = ((state.priceCentsPerKwh - ELECTRICITY_DATASET.nationalAverage) / ELECTRICITY_DATASET.nationalAverage) * 100; return <Card><CardHeader><div className="flex items-start justify-between gap-2"><div><CardTitle>{state.name}</CardTitle><CardDescription>Pinned state · {state.state}</CardDescription></div><button onClick={onClear} aria-label="Clear selection" className="inline-flex size-6 items-center justify-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground"><X className="size-4" /></button></div></CardHeader><CardContent className="space-y-4"><div className="flex items-baseline gap-2"><span className="text-3xl font-bold tabular-nums leading-none">{price(state.priceCentsPerKwh)}</span><span className="text-xs text-muted-foreground">per kWh</span></div><Separator /><Info label="National rank" value={`#${state.rank} cheapest of 50`} /><Info label="Vs. U.S. average" value={`${difference >= 0 ? "+" : ""}${difference.toFixed(1)}%`} /><Info label="Affordability score" value={`${state.affordabilityScore.toFixed(1)} / 100`} /><Info label="Map price band" value={state.priceBand} /></CardContent></Card>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 text-sm"><span className="text-muted-foreground">{label}</span><span className="text-right font-semibold tabular-nums">{value}</span></div>; }
function Sources() { return <Card size="sm"><CardHeader><CardTitle className="text-sm">Sources, methodology & limitations</CardTitle><CardDescription>{ELECTRICITY_DATASET.period} state comparison</CardDescription></CardHeader><CardContent className="space-y-4 text-sm leading-6 text-muted-foreground"><p><span className="font-medium text-foreground">Source.</span> <a className="font-medium text-foreground underline underline-offset-2" href={ELECTRICITY_DATASET.sourceUrl} target="_blank" rel="noreferrer">{ELECTRICITY_DATASET.sourceLabel}</a>; released {ELECTRICITY_DATASET.releaseDate} and based on Form EIA-861M preliminary estimates.</p><p><span className="font-medium text-foreground">Methodology.</span> States are ordered from the lowest to highest average residential retail price. The choropleth uses the actual cents-per-kWh field, grouped into fixed price brackets; the accompanying affordability score is the supplied inverse min-max normalization where 100 is the lowest state price and 0 is the highest.</p><p><span className="font-medium text-foreground">Limitations.</span> This is price per kWh, not a typical monthly bill. Household use, fixed charges, taxes, climate, housing type, and utility territory also affect what a household pays.</p></CardContent></Card>; }
