import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { geoAlbersUsa, geoPath } from "d3";
import * as topojson from "topojson-client";
import atlas from "us-atlas/states-10m.json";
import { STATE_NAME_TO_ABBR } from "../lib/states";

type Atlas = {
  objects: { states: unknown };
};

const width = 960;
const height = 560;
const projection = geoAlbersUsa().scale(1280).translate([480, 290]);
const path = geoPath(projection);
const us = atlas as unknown as Atlas;
const collection = topojson.feature(us as never, us.objects.states as never) as unknown as {
  features: Array<{ properties: { name: string } }>;
};

const states = collection.features
  .map((feature) => {
    const name = feature.properties.name;
    const abbr = STATE_NAME_TO_ABBR[name];
    const d = path(feature as never);
    const centroid = path.centroid(feature as never);
    if (!abbr || !d || Number.isNaN(centroid[0])) return null;
    return { name, abbr, d, centroid };
  })
  .filter(Boolean);

const source = `// Generated by scripts/generate-us-state-shapes.ts. Do not edit by hand.\n\nexport type UsStateShape = {\n  name: string;\n  abbr: string;\n  d: string;\n  centroid: [number, number];\n};\n\nexport const US_STATE_SHAPES: UsStateShape[] = ${JSON.stringify(states)};\n`;

async function main() {
  await writeFile(resolve("lib/maps/us-state-shapes.ts"), source);
}

void main();
