# Generated by Django 4.2.25 on 2025-10-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City or town name', max_length=100)),
                ('state', models.CharField(help_text='State name', max_length=50)),
                ('match_score', models.IntegerField(default=0, help_text='Match score from 0-100')),
                ('avg_price', models.CharField(help_text="Average home price (formatted, e.g., '$385k')", max_length=20)),
                ('climate', models.CharField(help_text="Climate description (e.g., 'Warm', '4 Seasons')", max_length=50)),
                ('cost_of_living', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=20)),
                ('population', models.CharField(help_text="Population (formatted, e.g., '58k')", max_length=20)),
                ('tags', models.JSONField(default=list, help_text='List of activity/feature tags')),
                ('va_distance', models.CharField(help_text="Distance to nearest VA facility (e.g., '3 miles')", max_length=50)),
                ('emoji', models.CharField(default='📍', help_text='Emoji icon for the location', max_length=10)),
                ('gradient', models.CharField(default='linear-gradient(135deg, #667eea 0%, #764ba2 100%)', help_text='CSS gradient for card background', max_length=200)),
                ('featured', models.BooleanField(default=False, help_text='Whether this location is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_score', 'name'],
                'indexes': [models.Index(fields=['match_score'], name='locations_l_match_s_54e83a_idx'), models.Index(fields=['state'], name='locations_l_state_93f5bb_idx'), models.Index(fields=['featured'], name='locations_l_feature_a64c51_idx')],
            },
        ),
    ]
