# Generated by Django 4.2.25 on 2025-10-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='avg_high_summer',
            field=models.IntegerField(blank=True, help_text='Average high temp in summer (°F)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='avg_low_winter',
            field=models.IntegerField(blank=True, help_text='Average low temp in winter (°F)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='city_politics',
            field=models.CharField(blank=True, help_text='City political leaning', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='climate_detailed',
            field=models.CharField(blank=True, help_text='Detailed climate description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='col_index',
            field=models.IntegerField(blank=True, help_text='Cost of living index (100=avg)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='county',
            field=models.CharField(blank=True, help_text='County name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='defense_hub',
            field=models.CharField(blank=True, help_text='Defense/military hub (Y/N)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='density',
            field=models.CharField(blank=True, help_text='Population density per sq mi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, help_text='Location description', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='distance_to_va',
            field=models.CharField(blank=True, help_text='Distance to VA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='election_2016',
            field=models.CharField(blank=True, help_text='2016 presidential winner', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='election_2016_percent',
            field=models.IntegerField(blank=True, help_text='2016 winner percentage', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='election_2024',
            field=models.CharField(blank=True, help_text='2024 presidential winner', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='election_2024_percent',
            field=models.IntegerField(blank=True, help_text='2024 winner percentage', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='election_change',
            field=models.CharField(blank=True, help_text='Voting shift 2016-2024', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='gas_price',
            field=models.CharField(blank=True, help_text='Average gas price', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='governor',
            field=models.CharField(blank=True, help_text="Governor's party (R/D)", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='has_va',
            field=models.CharField(blank=True, help_text='Has VA facility (Yes/No)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='humidity_summer',
            field=models.IntegerField(blank=True, help_text='Average July humidity %', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='income_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Income tax %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lgbtq_rating',
            field=models.CharField(blank=True, help_text='LGBTQ friendliness', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='marijuana_status',
            field=models.CharField(blank=True, help_text='Marijuana legal status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='nearest_va',
            field=models.CharField(blank=True, help_text='Nearest VA facility name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='population_raw',
            field=models.CharField(blank=True, help_text='Population (raw from CSV)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='rain_annual',
            field=models.IntegerField(blank=True, help_text='Average annual rainfall (inches)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='sales_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sales tax %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='snow_annual',
            field=models.IntegerField(blank=True, help_text='Average annual snowfall (inches)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='state_party',
            field=models.CharField(blank=True, help_text='State political party (R/D)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='sun_days',
            field=models.IntegerField(blank=True, help_text='Average sunny days per year', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='tci',
            field=models.IntegerField(blank=True, help_text='Total crime index (lower is safer)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='tech_hub',
            field=models.CharField(blank=True, help_text='Tech hub (Y/N)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='veterans_benefits',
            field=models.TextField(blank=True, help_text='Veteran-specific benefits', null=True),
        ),
    ]
