# Generated by Django 4.2.25 on 2025-10-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_avg_high_summer_location_avg_low_winter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('state', models.CharField(help_text='Two-letter state abbreviation', max_length=2, primary_key=True, serialize=False)),
                ('magazine_limit', models.TextField(blank=True, help_text='Magazine capacity restrictions', null=True)),
                ('gifford_score', models.CharField(blank=True, help_text='Giffords Law Center grade (A-F with +/-)', max_length=5, null=True)),
                ('ghost_gun_ban', models.CharField(blank=True, help_text='Ghost gun ban status (Y/N)', max_length=5, null=True)),
                ('assault_weapon_ban', models.CharField(blank=True, help_text='Assault weapon ban status (Y/N)', max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State Information',
                'verbose_name_plural': 'State Information',
                'ordering': ['state'],
            },
        ),
    ]
