# Generated by Django 4.2.27 on 2025-12-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_stateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='avg_home_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average home value (numeric)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='avg_home_value_display',
            field=models.CharField(blank=True, help_text="Formatted home value (e.g., '$385k')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='crime',
            field=models.CharField(blank=True, help_text='Crime rating/category', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='pps',
            field=models.IntegerField(blank=True, help_text='Per person spending or metric', null=True),
        ),
    ]
