# Generated by Django 4.2.27 on 2025-12-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_avg_home_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='climate_category',
            field=models.CharField(blank=True, choices=[('cold_snowy', 'Cold / Snowy'), ('hot_humid', 'Hot / Humid'), ('hot_dry', 'Hot / Dry'), ('mild_coastal', 'Mild / Coastal')], help_text='Computed climate category for filtering', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['climate_category'], name='locations_l_climate_80c4c6_idx'),
        ),
    ]
