# Generated by Django 4.2.30 on 2026-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_stateinfo_gun_law_booleans'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lgbtq_mei_score',
            field=models.IntegerField(blank=True, help_text='HRC Municipal Equality Index city score, where available (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lgbtq_score_source',
            field=models.CharField(blank=True, help_text='Source/method used for the LGBTQ friendliness score', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lgbtq_state_policy_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MAP overall state LGBTQ policy score out of 49', max_digits=5, null=True),
        ),
    ]
