# Generated by Django 4.2.30 on 2026-07-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_drop_dead_columns_rename_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='population',
            field=models.CharField(blank=True, help_text="Population (e.g., '915,927')", max_length=50, null=True),
        ),
    ]
